version: '3.8'

services:
  app:
    build: .
    container_name: reto4ad_app
    ports:
      - "8080:8080"
    environment:
      - SPRING_DATA_MONGODB_URI=mongodb+srv://root:root@cluster0.jj7aikx.mongodb.net/hoteles?retryWrites=true&w=majority
      - SPRING_DATA_MONGODB_DATABASE=hoteles
    restart: always